package org.fee.view;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;//for default table models
import org.fee.controller.PaymentDAO;
import org.fee.controller.StudentDAO;
//import org.fee.controller.SalesDAO;
import org.fee.util.Global;
import org.fee.model.*;


public class ManageFee extends javax.swing.JInternalFrame {

    /**
     * Creates new form SellProduct
     */ DefaultTableModel model;
    public ManageFee() {
       
        initComponents();
        jLabel_CurrentDate.setText(new Date().toString());
        jLabel_User.setText(Global.user);
        
    }
    public void clearFields()
    {
        jTextField_Id.setText("");
        jTextField_EName.setText("");
        jTextField_EFaculty.setText("");
        jTextField_ETotalFee.setText("");
        jTextField_EPaidAmount.setText("");
        jTextField_EDueAmount.setText("");
        jTextArea_ERemarks.setText("");
    }
    public void loadData(Student ob)
    {
        StudentDAO sDAO = new StudentDAO();
        int id=Integer.parseInt(jTextField_Id.getText());
        ob = sDAO.fetchDataById(id);
        jTextField_EName.setText(ob.getName());
        jTextField_EFaculty.setText(ob.getFaculty());
        jTextField_ETotalFee.setText(ob.getTotalfee()+"");
        jTextField_EPaidAmount.setText(ob.getPaidamount()+"");
        jTextField_EDueAmount.setText(ob.getDueamount()+"");
        jTextArea_ERemarks.setText(ob.getRemarks());
    }
    
    private void printBill()
    {
       
       String name = jTextField_EName.getText();
      String faculty =  jTextField_EFaculty.getText();
      int Paid = Integer.parseInt(jTextField_EPaidAmount.getText());
      String remarks = jTextArea_ERemarks.getText();
       
        String str="Orchid Billing System\n Bijaychowck,Kathmandu\n";
        
            str+="Name :"+name+" \n";
             str+="Faculty :"+faculty+" \n";
             str+="Payment Amount :"+Paid+"\n";
             str+="For "+remarks;
        
        str+="\n Thank You For Payment!!!";
        
        BillPrint ob=new BillPrint();
        ob.jTextArea_Bill.setLineWrap(true);
        ob.jTextArea_Bill.setText(str);
        try
        {
            ob.jTextArea_Bill.print();
                    
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel_CurrentDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jButton_SavePrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jTextField_EName = new javax.swing.JTextField();
        jTextField_EFaculty = new javax.swing.JTextField();
        jTextField_ETotalFee = new javax.swing.JTextField();
        jTextField_EPaidAmount = new javax.swing.JTextField();
        jTextField_EDueAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ERemarks = new javax.swing.JTextArea();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_LoadData = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);

        jLabel_CurrentDate.setText("Current Date");

        jLabel1.setText("Id");

        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jButton_SavePrint.setText("Save & Print");
        jButton_SavePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SavePrintActionPerformed(evt);
            }
        });

        jLabel2.setText("Logged in as :");

        jLabel_User.setText("User");

        jLabel6.setText("Name");

        jLabel7.setText("Faculty");

        jLabel3.setText("Total Fee");

        jLabel8.setText("Paid Amount");

        jLabel9.setText("Due Amount");

        jLabel4.setText("Remarks");

        jTextArea_ERemarks.setColumns(20);
        jTextArea_ERemarks.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ERemarks);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_LoadData.setText("Load Data");
        jButton_LoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Update)
                        .addGap(56, 56, 56)
                        .addComponent(jButton_Delete)
                        .addGap(43, 43, 43)
                        .addComponent(jButton_SavePrint))
                    .addComponent(jTextField_EName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_EFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ETotalFee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_EPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_EDueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_User))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CurrentDate)
                            .addComponent(jButton_LoadData))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel_CurrentDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_LoadData)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_EName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_EFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_ETotalFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_EPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_EDueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_SavePrint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_User)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed

    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jButton_SavePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SavePrintActionPerformed

       
           Payment ob=new Payment();
           String name = jTextField_EName.getText();
      String faculty =  jTextField_EFaculty.getText();
      int paid = Integer.parseInt(jTextField_EPaidAmount.getText());
      String remarks = jTextArea_ERemarks.getText();
      
           java.util.Date d=new java.util.Date();
           
          ob.setName(name);
          ob.setFaculty(faculty);
          ob.setPaidamt(paid);
          ob.setDop(d);
          ob.setRemarks(remarks);
           //list.add(ob);
      
       //for printing Bills
       printBill();
    }//GEN-LAST:event_jButton_SavePrintActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        int id=Integer.parseInt(jTextField_Id.getText());
        String name=jTextField_EName.getText();
        String faculty=jTextField_EFaculty.getText();
        int totalfee =Integer.parseInt(jTextField_ETotalFee.getText());
        int paidamount =Integer.parseInt(jTextField_EPaidAmount.getText());
        int dueAmount =Integer.parseInt(jTextField_EDueAmount.getText());
        String remarks=jTextArea_ERemarks.getText();
        //Set These Values In the "Model Class- Student " Object
        Student ob=new Student();
        ob.setId(id);
        ob.setName(name);
        ob.setFaculty(faculty);
        ob.setTotalfee(totalfee);
        ob.setPaidamount(paidamount);
        ob.setDueamount(dueAmount);
        ob.setRemarks(remarks);

        //Now handover This Object To the "Contoller Class  ProductDAO"
        StudentDAO pDAO=new StudentDAO();
        int count = pDAO.updateData(ob);
        if(count>0)
        {
            JOptionPane.showMessageDialog(null,"Record Updated");
            loadData(ob);
        }
        clearFields();

    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        int id=Integer.parseInt(jTextField_Id.getText());
        String name=jTextField_EName.getText();
        String faculty=jTextField_EFaculty.getText();
        int totalfee =Integer.parseInt(jTextField_ETotalFee.getText());
        int paidamount =Integer.parseInt(jTextField_EPaidAmount.getText());
        int dueAmount =Integer.parseInt(jTextField_EDueAmount.getText());
        String remarks=jTextArea_ERemarks.getText();
        //Set These Values In the "Model Class- product " Object
        Student ob=new Student();
        ob.setId(id);
        ob.setName(name);
        ob.setFaculty(faculty);
        ob.setTotalfee(totalfee);
        ob.setPaidamount(paidamount);
        ob.setDueamount(dueAmount);
        ob.setRemarks(remarks);

        //Now handover This Object To the "Contoller Class  ProductDAO"
        StudentDAO pDAO=new StudentDAO();
        int count = pDAO.deleteData(ob);
        if(count>0)
        {
            JOptionPane.showMessageDialog(null,"Record deleted");
            loadData(ob);
        }
        clearFields();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_LoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadDataActionPerformed
        //call fetchData() method of controller class
        Student ob = new Student();
        loadData(ob);
    }//GEN-LAST:event_jButton_LoadDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_LoadData;
    private javax.swing.JButton jButton_SavePrint;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CurrentDate;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_ERemarks;
    private javax.swing.JTextField jTextField_EDueAmount;
    private javax.swing.JTextField jTextField_EFaculty;
    private javax.swing.JTextField jTextField_EName;
    private javax.swing.JTextField jTextField_EPaidAmount;
    private javax.swing.JTextField jTextField_ETotalFee;
    private javax.swing.JTextField jTextField_Id;
    // End of variables declaration//GEN-END:variables
}
